<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api;
Route::post('/register', [Api\AuthController::class, 'register'])->middleware(['web', 'throttle:auth']);
Route::post('/login', [Api\AuthController::class, 'login'])->middleware(['web', 'throttle:auth']);
Route::post('/logout', [Api\AuthController::class, 'logout'])->middleware('web');
Route::post('/password/email', [Api\ForgotPasswordController::class, 'sendResetLink'])->middleware('throttle:password-reset');
Route::middleware('auth')->group(function () {
  Route::post('/locale/change', [Api\LocaleController::class, 'change']);
  Route::get('/locale/current', [Api\LocaleController::class, 'current']);
  Route::put('/profile', [Api\ProfileController::class, 'update']);
  Route::put('/profile/settings', [Api\ProfileController::class, 'updateSettings']);
  Route::put('/profile/preferences', [Api\ProfileController::class, 'updatePreferences']);
  Route::post('/lessons/{lessonId}/complete', [Api\LessonController::class, 'markComplete']);
  Route::post('/assessments/{assessmentId}/submit', [Api\AssessmentController::class, 'submit']);
  Route::post('/notifications/{notificationId}/read', [Api\NotificationController::class, 'markAsRead']);
  Route::get('/bookmarks', [Api\BookmarkController::class, 'index']);
  Route::post('/bookmarks', [Api\BookmarkController::class, 'store']);
  Route::delete('/bookmarks/{bookmarkId}', [Api\BookmarkController::class, 'destroy']);
  Route::get('/wishlist', [Api\WishlistController::class, 'index']);
  Route::post('/wishlist', [Api\WishlistController::class, 'store']);
  Route::delete('/wishlist/{wishlistId}', [Api\WishlistController::class, 'destroy']);
  Route::post('/discussion/threads', [Api\DiscussionController::class, 'storeThread']);
  Route::post('/discussion/posts', [Api\DiscussionController::class, 'storePost']);
  Route::post('/reviews', [Api\ReviewController::class, 'store']);
  Route::post('/notes', [Api\NoteController::class, 'store']);
  Route::post('/payments', [Api\PaymentController::class, 'create']);
  Route::post('/payments/{transactionId}/complete', [Api\PaymentController::class, 'complete']);
  Route::post('/coupons/apply', [Api\CouponController::class, 'apply']);
  Route::post('/gifts/redeem', [Api\GiftController::class, 'redeem']);
  Route::post('/peerReviews', [Api\PeerReviewController::class, 'store']);
  Route::post('/email/verificationNotification', [Api\EmailVerificationController::class, 'send']);
  Route::get('/oauth/{provider}', [Api\OAuthController::class, 'redirectToProvider'])->name('oauth.redirect');
  Route::post('/oauth/{provider}/callback', [Api\OAuthController::class, 'handleProviderCallback'])->name('oauth.callback');
  Route::post('/supportTickets', [Api\SupportTicketController::class, 'store']);
  Route::post('/supportTickets/{ticketId}/reply', [Api\SupportTicketController::class, 'reply']);
  Route::post('/supportTickets/{ticketId}/close', [Api\SupportTicketController::class, 'close']);
  Route::post('/affiliate/generateCode', [Api\AffiliateController::class, 'generateCode']);
  Route::prefix('instructor')->middleware('role:instructor')->group(function () {
    Route::post('/courses', [Api\Instructor\CourseManagementController::class, 'store']);
    Route::post('/modules', [Api\Instructor\SyllabusController::class, 'storeModule']);
    Route::post('/lessons', [Api\Instructor\SyllabusController::class, 'storeLesson']);
    Route::post('/assessments', [Api\Instructor\AssessmentBuilderController::class, 'store']);
    Route::post('/grading/{submissionId}', [Api\Instructor\GradingController::class, 'grade']);
  });
});