<?php
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CourseCatalogController;
use App\Http\Controllers\Api\CourseDetailController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\LessonController;
use App\Http\Controllers\Api\AssessmentController;
use App\Http\Controllers\Api\CertificateController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\Instructor\CourseManagementController;
use App\Http\Controllers\Api\Instructor\SyllabusController;
use App\Http\Controllers\Api\Instructor\AssessmentBuilderController;
use App\Http\Controllers\Api\Admin\UserManagementController;
use App\Http\Controllers\Api\Admin\CategoryController as AdminCategoryController;
use Illuminate\Support\Facades\Route;
Route::post('/register', [AuthController::class, 'register']);
Route::post('/login', [AuthController::class, 'login']);
Route::get('/courses', [CourseCatalogController::class, 'index']);
Route::get('/courses/{courseId}', [CourseDetailController::class, 'show']);
Route::get('/categories', [AdminCategoryController::class, 'index']);
Route::get('/certificates/verify/{uniqueCode}', [CertificateController::class, 'verify']);
Route::middleware('auth:sanctum')->group(function ()
{
  Route::post('/logout', [AuthController::class, 'logout']);
  Route::get('/user', [AuthController::class, 'user']);
  Route::get('/dashboard', [DashboardController::class, 'index']);
  Route::get('/lessons/{lessonId}', [LessonController::class, 'show']);
  Route::post('/lessons/{lessonId}/complete', [LessonController::class, 'markComplete']);
  Route::get('/assessments/{assessmentId}', [AssessmentController::class, 'show']);
  Route::post('/assessments/{assessmentId}/submit', [AssessmentController::class, 'submit']);
  Route::post('/courses/{courseId}/certificate', [CertificateController::class, 'generate']);
  Route::get('/courses/{courseId}/discussions', [\App\Http\Controllers\Api\DiscussionController::class, 'getThreads']);
  Route::post('/courses/{courseId}/discussions', [\App\Http\Controllers\Api\DiscussionController::class, 'createThread']);
  Route::get('/discussions/{threadId}/posts', [\App\Http\Controllers\Api\DiscussionController::class, 'getPosts']);
  Route::post('/discussions/{threadId}/posts', [\App\Http\Controllers\Api\DiscussionController::class, 'createPost']);
  Route::post('/discussions/posts/{postId}/accept', [\App\Http\Controllers\Api\DiscussionController::class, 'markAsAccepted']);
  Route::post('/discussions/{threadId}/pin', [\App\Http\Controllers\Api\DiscussionController::class, 'togglePin']);
  Route::post('/discussions/{threadId}/close', [\App\Http\Controllers\Api\DiscussionController::class, 'closeThread']);
  Route::post('/courses/{courseId}/enroll', [PaymentController::class, 'initiateEnrollment']);
  Route::post('/payments/{transactionId}/confirm', [PaymentController::class, 'confirmPayment']);
  Route::get('/payments/transactions', [PaymentController::class, 'transactions']);
  Route::get('/notifications', [\App\Http\Controllers\Api\NotificationController::class, 'index']);
  Route::post('/notifications/{notificationId}/read', [\App\Http\Controllers\Api\NotificationController::class, 'markAsRead']);
  Route::post('/notifications/readAll', [\App\Http\Controllers\Api\NotificationController::class, 'markAllAsRead']);
  Route::delete('/notifications/{notificationId}', [\App\Http\Controllers\Api\NotificationController::class, 'destroy']);
  Route::get('/notifications/unreadCount', [\App\Http\Controllers\Api\NotificationController::class, 'getUnreadCount']);
  Route::get('/profile', [\App\Http\Controllers\Api\ProfileController::class, 'show']);
  Route::put('/profile', [\App\Http\Controllers\Api\ProfileController::class, 'update']);
  Route::get('/bookmarks', [\App\Http\Controllers\Api\BookmarkController::class, 'index']);
  Route::post('/bookmarks/{lessonId}/toggle', [\App\Http\Controllers\Api\BookmarkController::class, 'toggle']);
  Route::post('/bookmarks/{bookmarkId}/note', [\App\Http\Controllers\Api\BookmarkController::class, 'addNote']);
  Route::get('/calendar/events', [\App\Http\Controllers\Api\CalendarController::class, 'getEvents']);
  Route::get('/courses/{courseId}/reviews', [\App\Http\Controllers\Api\ReviewController::class, 'index']);
  Route::post('/courses/{courseId}/reviews', [\App\Http\Controllers\Api\ReviewController::class, 'store']);
  Route::post('/reviews/{reviewId}/respond', [\App\Http\Controllers\Api\ReviewController::class, 'respond']);
  Route::post('/reviews/{reviewId}/helpful', [\App\Http\Controllers\Api\ReviewController::class, 'markHelpful']);
  Route::get('/wishlist', [\App\Http\Controllers\Api\WishlistController::class, 'index']);
  Route::post('/wishlist/{courseId}/toggle', [\App\Http\Controllers\Api\WishlistController::class, 'toggle']);
  Route::get('/gamification/stats', [\App\Http\Controllers\Api\GamificationController::class, 'getStats']);
  Route::get('/gamification/leaderboard', [\App\Http\Controllers\Api\GamificationController::class, 'getLeaderboard']);
  Route::post('/coupons/validate', [\App\Http\Controllers\Api\CouponController::class, 'validate']);
  Route::post('/coupons/apply', [\App\Http\Controllers\Api\CouponController::class, 'apply']);
  Route::get('/notes', [\App\Http\Controllers\Api\NoteController::class, 'index']);
  Route::get('/lessons/{lessonId}/notes', [\App\Http\Controllers\Api\NoteController::class, 'getLessonNotes']);
  Route::post('/notes', [\App\Http\Controllers\Api\NoteController::class, 'store']);
  Route::put('/notes/{noteId}', [\App\Http\Controllers\Api\NoteController::class, 'update']);
  Route::delete('/notes/{noteId}', [\App\Http\Controllers\Api\NoteController::class, 'destroy']);
  Route::get('/bundles', [\App\Http\Controllers\Api\BundleController::class, 'index']);
  Route::get('/bundles/{bundleId}', [\App\Http\Controllers\Api\BundleController::class, 'show']);
  Route::post('/gifts/purchase', [\App\Http\Controllers\Api\GiftController::class, 'purchase']);
  Route::post('/gifts/redeem', [\App\Http\Controllers\Api\GiftController::class, 'redeem']);
  Route::get('/gifts/{giftCode}/check', [\App\Http\Controllers\Api\GiftController::class, 'check']);
  Route::get('/peerReviews/assigned', [\App\Http\Controllers\Api\PeerReviewController::class, 'getAssignedReviews']);
  Route::post('/peerReviews/{peerReviewId}/submit', [\App\Http\Controllers\Api\PeerReviewController::class, 'submitReview']);
  Route::get('/submissions/{submissionId}/peerReviews', [\App\Http\Controllers\Api\PeerReviewController::class, 'getReceivedReviews']);
  Route::prefix('instructor')->middleware('can:isAdminOrInstructor')->group(function ()
  {
    Route::get('/courses', [CourseManagementController::class, 'index']);
    Route::post('/courses', [CourseManagementController::class, 'store']);
    Route::get('/courses/{courseId}', [CourseManagementController::class, 'show']);
    Route::put('/courses/{courseId}', [CourseManagementController::class, 'update']);
    Route::delete('/courses/{courseId}', [CourseManagementController::class, 'destroy']);
    Route::post('/courses/{courseId}/publish', [CourseManagementController::class, 'publish']);
    Route::post('/courses/{courseId}/modules', [SyllabusController::class, 'addModule']);
    Route::put('/modules/{moduleId}', [SyllabusController::class, 'updateModule']);
    Route::delete('/modules/{moduleId}', [SyllabusController::class, 'deleteModule']);
    Route::post('/modules/{moduleId}/lessons', [SyllabusController::class, 'addLesson']);
    Route::put('/lessons/{lessonId}', [SyllabusController::class, 'updateLesson']);
    Route::delete('/lessons/{lessonId}', [SyllabusController::class, 'deleteLesson']);
    Route::post('/lessons/{lessonId}/assessments', [AssessmentBuilderController::class, 'store']);
    Route::put('/assessments/{assessmentId}', [AssessmentBuilderController::class, 'update']);
    Route::delete('/assessments/{assessmentId}', [AssessmentBuilderController::class, 'destroy']);
    Route::get('/submissions', [\App\Http\Controllers\Api\Instructor\GradingController::class, 'getSubmissions']);
    Route::post('/submissions/{submissionId}/grade', [\App\Http\Controllers\Api\Instructor\GradingController::class, 'submitGrade']);
    Route::get('/courses/{courseId}/submissions', [\App\Http\Controllers\Api\Instructor\GradingController::class, 'getCourseSubmissions']);
  });
  Route::prefix('admin')->middleware('can:isAdmin')->group(function ()
  {
    Route::get('/dashboard', [\App\Http\Controllers\Api\Admin\AdminDashboardController::class, 'index']);
    Route::get('/users', [UserManagementController::class, 'index']);
    Route::post('/users', [UserManagementController::class, 'store']);
    Route::put('/users/{userId}', [UserManagementController::class, 'update']);
    Route::delete('/users/{userId}', [UserManagementController::class, 'destroy']);
    Route::post('/categories', [AdminCategoryController::class, 'store']);
    Route::put('/categories/{categoryId}', [AdminCategoryController::class, 'update']);
    Route::delete('/categories/{categoryId}', [AdminCategoryController::class, 'destroy']);
  });
});