<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api;
Route::post('/register', [Api\AuthController::class, 'register'])->middleware(['web', 'throttle:auth']);
Route::post('/login', [Api\AuthController::class, 'login'])->middleware(['web', 'throttle:auth']);
Route::post('/logout', [Api\AuthController::class, 'logout'])->middleware('web');
Route::post('/password/email', [Api\ForgotPasswordController::class, 'sendResetLink'])->middleware('throttle:password-reset');
Route::middleware('auth')->group(function () {
  Route::post('/locale/change', [Api\LocaleController::class, 'change']);
  Route::get('/locale/current', [Api\LocaleController::class, 'current']);
  Route::get('/dashboard', [Api\DashboardController::class, 'index']);
  Route::get('/analytics', [Api\AnalyticsController::class, 'index']);
  Route::get('/profile', [Api\ProfileController::class, 'show']);
  Route::put('/profile', [Api\ProfileController::class, 'update']);
  Route::get('/courses', [Api\CourseCatalogController::class, 'index']);
  Route::get('/courses/{courseId}', [Api\CourseDetailController::class, 'show']);
  Route::get('/lessons/{lessonId}', [Api\LessonController::class, 'show'])->middleware(App\Http\Middleware\LessonAccessMiddleware::class);
  Route::post('/lessons/{lessonId}/complete', [Api\LessonController::class, 'markComplete']);
  Route::get('/assessments/{assessmentId}', [Api\AssessmentController::class, 'show']);
  Route::post('/assessments/{assessmentId}/submit', [Api\AssessmentController::class, 'submit']);
  Route::get('/calendar', [Api\CalendarController::class, 'index']);
  Route::get('/notifications', [Api\NotificationController::class, 'index']);
  Route::post('/notifications/{notificationId}/read', [Api\NotificationController::class, 'markAsRead']);
  Route::get('/certificates', [Api\CertificateController::class, 'index']);
  Route::get('/certificates/{certificateId}', [Api\CertificateController::class, 'show']);
  Route::get('/bookmarks', [Api\BookmarkController::class, 'index']);
  Route::post('/bookmarks', [Api\BookmarkController::class, 'store']);
  Route::delete('/bookmarks/{bookmarkId}', [Api\BookmarkController::class, 'destroy']);
  Route::get('/wishlist', [Api\WishlistController::class, 'index']);
  Route::post('/wishlist', [Api\WishlistController::class, 'store']);
  Route::delete('/wishlist/{wishlistId}', [Api\WishlistController::class, 'destroy']);
  Route::get('/bundles', [Api\BundleController::class, 'index']);
  Route::get('/courses/{courseId}/discussion', [Api\DiscussionController::class, 'index']);
  Route::post('/discussion/threads', [Api\DiscussionController::class, 'storeThread']);
  Route::post('/discussion/posts', [Api\DiscussionController::class, 'storePost']);
  Route::get('/courses/{courseId}/reviews', [Api\ReviewController::class, 'index']);
  Route::post('/reviews', [Api\ReviewController::class, 'store']);
  Route::post('/notes', [Api\NoteController::class, 'store']);
  Route::get('/leaderboard', [Api\GamificationController::class, 'index']);
  Route::post('/payments', [Api\PaymentController::class, 'create']);
  Route::post('/payments/{transactionId}/complete', [Api\PaymentController::class, 'complete']);
  Route::post('/coupons/apply', [Api\CouponController::class, 'apply']);
  Route::post('/gifts/redeem', [Api\GiftController::class, 'redeem']);
  Route::post('/peerReviews', [Api\PeerReviewController::class, 'store']);
  Route::post('/email/verificationNotification', [Api\EmailVerificationController::class, 'send']);
  Route::get('/oauth/{provider}', [Api\OAuthController::class, 'redirectToProvider'])->name('oauth.redirect');
  Route::post('/oauth/{provider}/callback', [Api\OAuthController::class, 'handleProviderCallback'])->name('oauth.callback');
  Route::get('/supportTickets', [Api\SupportTicketController::class, 'index']);
  Route::post('/supportTickets', [Api\SupportTicketController::class, 'store']);
  Route::get('/supportTickets/{ticketId}', [Api\SupportTicketController::class, 'show']);
  Route::post('/supportTickets/{ticketId}/reply', [Api\SupportTicketController::class, 'reply']);
  Route::post('/supportTickets/{ticketId}/close', [Api\SupportTicketController::class, 'close']);
  Route::put('/profile/settings', [Api\ProfileController::class, 'updateSettings']);
  Route::put('/profile/preferences', [Api\ProfileController::class, 'updatePreferences']);
  Route::get('/affiliate/dashboard', [Api\AffiliateController::class, 'dashboard']);
  Route::post('/affiliate/generateCode', [Api\AffiliateController::class, 'generateCode']);
  Route::prefix('instructor')->middleware('role:instructor')->group(function () {
    Route::get('/dashboard', [Api\Instructor\CourseManagementController::class, 'index']);
    Route::post('/courses', [Api\Instructor\CourseManagementController::class, 'store']);
    Route::post('/modules', [Api\Instructor\SyllabusController::class, 'storeModule']);
    Route::post('/lessons', [Api\Instructor\SyllabusController::class, 'storeLesson']);
    Route::post('/assessments', [Api\Instructor\AssessmentBuilderController::class, 'store']);
    Route::get('/grading', [Api\Instructor\GradingController::class, 'index']);
    Route::post('/grading/{submissionId}', [Api\Instructor\GradingController::class, 'grade']);
  });
  Route::prefix('admin')->middleware('role:admin')->group(function () {
    Route::get('/dashboard', [Api\Admin\AdminDashboardController::class, 'index']);
    Route::get('/users', [Api\Admin\UserManagementController::class, 'index']);
    Route::put('/users/{userId}/role', [Api\Admin\UserManagementController::class, 'updateRole']);
    Route::delete('/users/{userId}', [Api\Admin\UserManagementController::class, 'destroy']);
    Route::post('/categories', [Api\Admin\CategoryController::class, 'store']);
    Route::put('/categories/{categoryId}', [Api\Admin\CategoryController::class, 'update']);
    Route::get('/transactions', [Api\Admin\TransactionManagementController::class, 'index']);
    Route::get('/transactions/{transactionId}', [Api\Admin\TransactionManagementController::class, 'show']);
    Route::post('/transactions/{transactionId}/approve', [Api\Admin\TransactionManagementController::class, 'approve']);
    Route::post('/transactions/{transactionId}/reject', [Api\Admin\TransactionManagementController::class, 'reject']);
    Route::post('/transactions/{transactionId}/refund', [Api\Admin\TransactionManagementController::class, 'refund']);
  });
});