<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Public;
use App\Http\Controllers\Auth;
use App\Http\Controllers\Learner;
use App\Http\Controllers\Instructor;
use App\Http\Controllers\Shared;
use App\Http\Controllers\Admin;
use App\Http\Middleware\AdminRouteMiddleware;
Route::get('/', [Public\HomeController::class, 'index']);
Route::get('/courses', [Public\CourseController::class, 'index']);
Route::get('/courses/{courseId}', [Public\CourseController::class, 'show']);
Route::get('/login', [Auth\AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [Auth\AuthController::class, 'login']);
Route::get('/register', [Auth\AuthController::class, 'showRegister'])->name('register');
Route::post('/register', [Auth\AuthController::class, 'register']);
Route::post('/logout', [Auth\AuthController::class, 'logout'])->name('logout');
Route::get('/forgotPassword', [Auth\ForgotPasswordController::class, 'showLinkRequestForm'])->name('forgotPassword');
Route::post('/forgotPassword', [Auth\ForgotPasswordController::class, 'sendResetLink'])->name('sendResetLink');
Route::get('/passwordReset', [Auth\ForgotPasswordController::class, 'showResetForm'])->name('passwordReset');
Route::post('/passwordReset', [Auth\ForgotPasswordController::class, 'reset'])->name('password.update');
Route::get('/email/verify/{token}', [Auth\EmailVerificationController::class, 'verify'])->name('verification.verify');
Route::get('/oauth/{provider}', [Auth\OAuthController::class, 'redirectToProvider'])->name('oauth.redirect');
Route::get('/oauth/{provider}/callback', [Auth\OAuthController::class, 'handleProviderCallback'])->name('oauth.callback');
Route::get('/twoFactorChallenge', [Auth\TwoFactorController::class, 'showChallenge']);
Route::post('/twoFactorChallenge', [Auth\AuthController::class, 'verifyTwoFactor']);
Route::middleware(['auth', AdminRouteMiddleware::class])->group(function () {
  Route::get('/dashboard', [Learner\DashboardController::class, 'index'])->name('dashboard');
  Route::get('/settings', [Shared\SettingsController::class, 'index'])->name('settings');
  Route::get('/lessons/{lessonId}', [Learner\LessonController::class, 'show']);
  Route::get('/courses/{courseId}/learn', [Learner\CourseController::class, 'learn']);
  Route::get('/courses/{courseId}/reviews', [Learner\ReviewController::class, 'index']);
  Route::post('/api/courses/{courseId}/reviews', [Learner\ReviewController::class, 'store']);
  Route::get('/wishlist', [Learner\WishlistController::class, 'index'])->name('wishlist');
  Route::post('/api/wishlist/toggle', [Learner\WishlistController::class, 'toggle'])->name('wishlist.toggle');
  Route::get('/certificates', [Learner\CertificateController::class, 'index'])->name('certificates');
  Route::get('/certificates/{certificateId}', [Learner\CertificateController::class, 'show'])->name('certificates.view');
  Route::get('/notifications', [Shared\NotificationController::class, 'index'])->name('notifications');
  Route::post('/api/notifications/{notificationId}/read', [Shared\NotificationController::class, 'markAsRead']);
  Route::post('/api/notifications/readAll', [Shared\NotificationController::class, 'markAllAsRead']);
  Route::delete('/api/notifications/{notificationId}', [Shared\NotificationController::class, 'destroy']);
  Route::get('/supportTickets', [Shared\SupportTicketController::class, 'index'])->name('supportTickets');
  Route::post('/api/supportTickets', [Shared\SupportTicketController::class, 'store']);
  Route::get('/supportTickets/{ticketId}', [Shared\SupportTicketController::class, 'show']);
  Route::post('/api/supportTickets/{ticketId}/reply', [Shared\SupportTicketController::class, 'reply']);
  Route::post('/api/supportTickets/{ticketId}/close', [Shared\SupportTicketController::class, 'close']);
  Route::post('/user/twoFactorAuthentication', [Auth\TwoFactorController::class, 'enable'])->name('twoFactor.enable');
  Route::post('/user/confirmedTwoFactorAuthentication', [Auth\TwoFactorController::class, 'confirm'])->name('twoFactor.confirm');
  Route::delete('/user/twoFactorAuthentication', [Auth\TwoFactorController::class, 'disable'])->name('twoFactor.disable');
  Route::post('/api/payment/create', [Learner\PaymentController::class, 'create']);
  Route::get('/quiz/{quizId}', [Learner\QuizController::class, 'show']);
  Route::post('/api/quiz/{quizId}/submit', [Learner\QuizController::class, 'submit']);
  Route::get('/assessment/{assessmentId}', [Learner\AssessmentController::class, 'show']);
  Route::post('/api/assessment/{assessmentId}/submit', [Learner\AssessmentController::class, 'submit']);
  Route::post('/api/lessons/{lessonId}/complete', [Learner\LessonController::class, 'complete']);
});
Route::middleware(['auth', 'role:instructor'])->group(function () {
  Route::get('/instructor/dashboard', [Instructor\DashboardController::class, 'index']);
  Route::get('/instructor/courses/create', [Instructor\CourseManagementController::class, 'create']);
  Route::get('/instructor/courses/{courseId}/edit', [Instructor\CourseManagementController::class, 'edit']);
  Route::get('/instructor/grading', [Instructor\GradingController::class, 'index']);
  Route::get('/instructor/students', [Instructor\StudentController::class, 'index']);
  Route::get('/instructor/earnings', [Instructor\EarningsController::class, 'dashboard']);
  Route::get('/api/instructor/earnings/history', [Instructor\EarningsController::class, 'history']);
  Route::put('/api/instructor/bankInfo', [Instructor\EarningsController::class, 'updateBankInfo']);
  Route::post('/api/instructor/bankQr', [Instructor\EarningsController::class, 'uploadBankQr']);
  Route::post('/api/instructor/courses', [Instructor\CourseManagementController::class, 'store']);
  Route::put('/api/instructor/courses/{courseId}', [Instructor\CourseManagementController::class, 'update']);
  Route::post('/api/instructor/courses/{courseId}/modules', [Instructor\CourseManagementController::class, 'addModule']);
  Route::put('/api/instructor/modules/{moduleId}', [Instructor\CourseManagementController::class, 'updateModule']);
  Route::post('/api/instructor/modules/{moduleId}/reorder', [Instructor\CourseManagementController::class, 'reorderModule']);
  Route::delete('/api/instructor/modules/{moduleId}', [Instructor\CourseManagementController::class, 'deleteModule']);
  Route::post('/api/instructor/modules/{moduleId}/lessons', [Instructor\CourseManagementController::class, 'addLesson']);
  Route::delete('/api/instructor/lessons/{lessonId}', [Instructor\CourseManagementController::class, 'deleteLesson']);
  Route::delete('/api/instructor/courses/{courseId}', [Instructor\CourseManagementController::class, 'deleteCourse']);
  Route::post('/api/instructor/courses/{courseId}/publish', [Instructor\CourseManagementController::class, 'publish']);
  Route::post('/api/instructor/submissions/{submissionId}/grade', [Instructor\GradingController::class, 'grade']);
  Route::post('/api/instructor/lessons/{lessonId}/content', [Instructor\LessonContentController::class, 'uploadContent']);
  Route::get('/api/instructor/lessons/{lessonId}/content', [Instructor\LessonContentController::class, 'getContent']);
  Route::get('/api/instructor/courses/{courseId}/quiz', [Instructor\QuizController::class, 'getQuiz']);
  Route::post('/api/instructor/courses/{courseId}/quiz', [Instructor\QuizController::class, 'saveQuiz']);
  Route::post('/api/instructor/quizzes/{quizId}/questions', [Instructor\QuizController::class, 'addQuestion']);
  Route::put('/api/instructor/questions/{questionId}', [Instructor\QuizController::class, 'updateQuestion']);
  Route::delete('/api/instructor/questions/{questionId}', [Instructor\QuizController::class, 'deleteQuestion']);
  Route::get('/api/instructor/courses/{courseId}/assessment', [Instructor\AssessmentController::class, 'getAssessment']);
  Route::post('/api/instructor/courses/{courseId}/assessment', [Instructor\AssessmentController::class, 'saveAssessment']);
});
Route::prefix('admin')->middleware(['auth', 'role:admin'])->group(function () {
  Route::get('/dashboard', [Admin\AnalyticsController::class, 'getDashboardData']);
  Route::post('/uploadQr', [Admin\SettingsController::class, 'uploadQr']);
  Route::get('/users/export', [Admin\UserController::class, 'export']);
  Route::get('/users', [Admin\UserController::class, 'index']);
  Route::post('/users', [Admin\UserController::class, 'store']);
  Route::put('/users/{userId}', [Admin\UserController::class, 'update']);
  Route::delete('/users/{userId}', [Admin\UserController::class, 'destroy']);
  Route::get('/courses/export', [Admin\CourseController::class, 'export']);
  Route::get('/courses', [Admin\CourseController::class, 'index']);
  Route::post('/courses', [Admin\CourseController::class, 'store']);
  Route::put('/courses/{courseId}', [Admin\CourseController::class, 'update']);
  Route::delete('/courses/{courseId}', [Admin\CourseController::class, 'destroy']);
  Route::get('/categories/export', [Admin\CategoryController::class, 'export']);
  Route::get('/categories', [Admin\CategoryController::class, 'index']);
  Route::post('/categories', [Admin\CategoryController::class, 'store']);
  Route::put('/categories/{categoryId}', [Admin\CategoryController::class, 'update']);
  Route::delete('/categories/{categoryId}', [Admin\CategoryController::class, 'destroy']);
  Route::get('/reviews/export', [Admin\ReviewController::class, 'export']);
  Route::get('/reviews', [Admin\ReviewController::class, 'index']);
  Route::post('/reviews', [Admin\ReviewController::class, 'store']);
  Route::put('/reviews/{reviewId}', [Admin\ReviewController::class, 'update']);
  Route::delete('/reviews/{reviewId}', [Admin\ReviewController::class, 'destroy']);
  Route::get('/enrollments/export', [Admin\EnrollmentController::class, 'export']);
  Route::get('/enrollments', [Admin\EnrollmentController::class, 'index']);
  Route::post('/enrollments', [Admin\EnrollmentController::class, 'store']);
  Route::put('/enrollments/{userId}/{courseId}', [Admin\EnrollmentController::class, 'update']);
  Route::delete('/enrollments/{userId}/{courseId}', [Admin\EnrollmentController::class, 'destroy']);
  Route::get('/support/export', [Admin\SupportTicketController::class, 'export']);
  Route::get('/support', [Admin\SupportTicketController::class, 'index']);
  Route::post('/support', [Admin\SupportTicketController::class, 'store']);
  Route::put('/support/{ticketId}', [Admin\SupportTicketController::class, 'update']);
  Route::delete('/support/{ticketId}', [Admin\SupportTicketController::class, 'destroy']);
  Route::get('/certificates/export', [Admin\CertificateController::class, 'export']);
  Route::get('/certificates', [Admin\CertificateController::class, 'index']);
  Route::post('/certificates', [Admin\CertificateController::class, 'store']);
  Route::put('/certificates/{certificateId}', [Admin\CertificateController::class, 'update']);
  Route::delete('/certificates/{certificateId}', [Admin\CertificateController::class, 'destroy']);
  Route::get('/notifications/export', [Admin\NotificationController::class, 'export']);
  Route::get('/notifications', [Admin\NotificationController::class, 'index']);
  Route::post('/notifications', [Admin\NotificationController::class, 'store']);
  Route::put('/notifications/{notificationId}', [Admin\NotificationController::class, 'update']);
  Route::delete('/notifications/{notificationId}', [Admin\NotificationController::class, 'destroy']);
  Route::get('/transactions/export', [Admin\TransactionController::class, 'export']);
  Route::get('/transactions', [Admin\TransactionController::class, 'index']);
  Route::post('/transactions/{transactionId}/confirm', [Learner\PaymentController::class, 'confirmPayment']);
  Route::get('/payouts', [Admin\PayoutController::class, 'index']);
  Route::get('/payouts/instructorBalances', [Admin\PayoutController::class, 'instructorBalances']);
  Route::post('/payouts', [Admin\PayoutController::class, 'create']);
  Route::post('/payouts/{payoutId}/process', [Admin\PayoutController::class, 'process']);
  Route::post('/payouts/{payoutId}/cancel', [Admin\PayoutController::class, 'cancel']);
});
Route::post('/language', [Shared\LanguageController::class, 'update'])->name('language.update');