<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration
{
  public function up(): void
  {
    Schema::create('users', function (Blueprint $table) {
      $table->id('userId');
      $table->string('userName');
      $table->string('userEmail')->unique();
      $table->string('password');
      $table->enum('role', ['admin', 'instructor', 'learner'])->default('learner');
      $table->text('twoFactorSecret')->nullable();
      $table->text('twoFactorRecoveryCodes')->nullable();
      $table->timestamp('twoFactorConfirmedAt')->nullable();
      $table->string('bankQrPath')->nullable();
      $table->string('bankName')->nullable();
      $table->string('bankAccountNumber')->nullable();
      $table->string('bankAccountName')->nullable();
      $table->timestamp('emailVerifiedAt')->nullable();
      $table->string('rememberToken', 100)->nullable();
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index('userEmail');
      $table->index('role');
    });
    Schema::create('passwordResetTokens', function (Blueprint $table) {
      $table->id('tokenId');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->string('token');
      $table->timestamp('expiresAt');
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index('token');
    });
    Schema::create('categories', function (Blueprint $table) {
      $table->id('categoryId');
      $table->string('categoryName');
      $table->string('slug')->unique();
      $table->string('icon')->nullable();
      $table->text('description')->nullable();
      $table->integer('courseCount')->default(0);
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index('slug');
    });
    Schema::create('courses', function (Blueprint $table) {
      $table->id('courseId');
      $table->string('courseTitle');
      $table->text('courseDescription');
      $table->decimal('simulatedPrice', 10, 2)->default(0);
      $table->string('courseImage')->nullable();
      $table->foreignId('instructorId')->constrained('users', 'userId')->onDelete('cascade');
      $table->foreignId('categoryId')->constrained('categories', 'categoryId')->onDelete('cascade');
      $table->jsonb('courseMeta')->nullable();
      $table->boolean('isPublished')->default(false);
      $table->decimal('averageRating', 3, 2)->default(0);
      $table->integer('totalEnrollments')->default(0);
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index('instructorId');
      $table->index('categoryId');
      $table->index('isPublished');
      $table->index(['isPublished', 'categoryId']);
    });
    Schema::create('modules', function (Blueprint $table) {
      $table->id('moduleId');
      $table->foreignId('courseId')->constrained('courses', 'courseId')->onDelete('cascade');
      $table->string('moduleTitle');
      $table->text('moduleDescription')->nullable();
      $table->integer('orderIndex')->default(0);
      $table->integer('durationMinutes')->default(0);
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index(['courseId', 'orderIndex']);
    });
    Schema::create('lessons', function (Blueprint $table) {
      $table->id('lessonId');
      $table->foreignId('moduleId')->constrained('modules', 'moduleId')->onDelete('cascade');
      $table->string('lessonTitle');
      $table->enum('contentType', ['text', 'video', 'pdf', 'quiz'])->default('text');
      $table->jsonb('contentData');
      $table->integer('orderIndex')->default(0);
      $table->integer('durationMinutes')->default(0);
      $table->boolean('isMandatory')->default(true);
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index(['moduleId', 'orderIndex']);
    });
    Schema::create('enrollments', function (Blueprint $table) {
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->foreignId('courseId')->constrained('courses', 'courseId')->onDelete('cascade');
      $table->timestamp('enrollmentDate')->useCurrent();
      $table->boolean('isPaid')->default(false);
      $table->decimal('completionPercent', 5, 2)->default(0);
      $table->timestamp('completedAt')->nullable();
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->primary(['userId', 'courseId']);
      $table->index('enrollmentDate');
      $table->index('isPaid');
      $table->index(['userId', 'isPaid']);
    });
    Schema::create('paymentTransactions', function (Blueprint $table) {
      $table->id('transactionId');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->foreignId('courseId')->constrained('courses', 'courseId')->onDelete('cascade');
      $table->decimal('amount', 10, 2);
      $table->decimal('instructorAmount', 12, 2)->nullable();
      $table->decimal('platformFee', 12, 2)->nullable();
      $table->timestamp('escrowReleasedAt')->nullable();
      $table->string('qrCodePath')->nullable();
      $table->enum('transactionStatus', ['pending', 'completed', 'failed', 'cancelled', 'refunded'])->default('pending');
      $table->boolean('isRefunded')->default(false);
      $table->decimal('refundAmount', 10, 2)->nullable();
      $table->timestamp('refundedAt')->nullable();
      $table->text('adminNotes')->nullable();
      $table->string('paymentMethod')->default('bankTransfer');
      $table->jsonb('transactionMeta')->nullable();
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index(['userId', 'transactionStatus']);
      $table->index('transactionStatus');
    });
    Schema::create('progress', function (Blueprint $table) {
      $table->id('progressId');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->foreignId('lessonId')->constrained('lessons', 'lessonId')->onDelete('cascade');
      $table->boolean('isCompleted')->default(false);
      $table->decimal('completionPercent', 5, 2)->default(0);
      $table->integer('timeSpentSeconds')->default(0);
      $table->decimal('score', 5, 2)->nullable();
      $table->timestamp('startedAt')->nullable();
      $table->timestamp('completedAt')->nullable();
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->unique(['userId', 'lessonId']);
      $table->index(['userId', 'isCompleted']);
      $table->index('isCompleted');
    });
    Schema::create('assessments', function (Blueprint $table) {
      $table->id('assessmentId');
      $table->foreignId('lessonId')->constrained('lessons', 'lessonId')->onDelete('cascade');
      $table->string('assessmentTitle');
      $table->enum('assessmentType', ['quiz', 'assignment', 'exam'])->default('quiz');
      $table->jsonb('questionData');
      $table->decimal('passingScore', 5, 2)->default(70.00);
      $table->integer('timeLimit')->nullable();
      $table->integer('maxAttempts')->default(3);
      $table->boolean('randomizeQuestions')->default(false);
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index('lessonId');
    });
    Schema::create('assessmentSubmissions', function (Blueprint $table) {
      $table->id('submissionId');
      $table->foreignId('assessmentId')->constrained('assessments', 'assessmentId')->onDelete('cascade');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->jsonb('answerData');
      $table->decimal('score', 5, 2)->nullable();
      $table->integer('attemptNumber')->default(1);
      $table->boolean('isPassed')->default(false);
      $table->text('instructorFeedback')->nullable();
      $table->timestamp('submittedAt')->useCurrent();
      $table->timestamp('gradedAt')->nullable();
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index(['userId', 'assessmentId']);
    });
    Schema::create('notifications', function (Blueprint $table) {
      $table->id('notificationId');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->string('notificationType');
      $table->string('notificationTitle');
      $table->text('notificationContent');
      $table->jsonb('notificationData')->nullable();
      $table->boolean('isRead')->default(false);
      $table->timestamp('readAt')->nullable();
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->index(['userId', 'isRead']);
      $table->index('isRead');
    });
    Schema::create('certificates', function (Blueprint $table) {
      $table->id('certificateId');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->foreignId('courseId')->constrained('courses', 'courseId')->onDelete('cascade');
      $table->string('uniqueCode')->unique();
      $table->string('pdfPath')->nullable();
      $table->timestamp('issuedAt')->useCurrent();
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->unique(['userId', 'courseId']);
      $table->index('uniqueCode');
    });
    Schema::create('courseReviews', function (Blueprint $table) {
      $table->id('reviewId');
      $table->unsignedBigInteger('courseId');
      $table->unsignedBigInteger('userId');
      $table->integer('rating')->unsigned()->default(5);
      $table->text('reviewText')->nullable();
      $table->text('instructorResponse')->nullable();
      $table->timestamp('respondedAt')->nullable();
      $table->integer('helpfulCount')->default(0);
      $table->integer('notHelpfulCount')->default(0);
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->foreign('courseId')->references('courseId')->on('courses')->onDelete('cascade');
      $table->foreign('userId')->references('userId')->on('users')->onDelete('cascade');
      $table->unique(['courseId', 'userId']);
      $table->index(['courseId', 'rating']);
    });
    Schema::create('wishlists', function (Blueprint $table) {
      $table->id('wishlistId');
      $table->unsignedBigInteger('userId');
      $table->unsignedBigInteger('courseId');
      $table->timestamp('createdAt')->useCurrent();
      $table->foreign('userId')->references('userId')->on('users')->onDelete('cascade');
      $table->foreign('courseId')->references('courseId')->on('courses')->onDelete('cascade');
      $table->unique(['userId', 'courseId']);
      $table->index('userId');
    });
    Schema::create('oauthProviders', function (Blueprint $table) {
      $table->id('oauthId');
      $table->unsignedBigInteger('userId');
      $table->string('provider');
      $table->string('providerId');
      $table->text('accessToken')->nullable();
      $table->text('refreshToken')->nullable();
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->foreign('userId')->references('userId')->on('users')->onDelete('cascade');
      $table->unique(['provider', 'providerId']);
      $table->index('userId');
    });
    Schema::create('supportTickets', function (Blueprint $table) {
      $table->id('ticketId');
      $table->unsignedBigInteger('userId');
      $table->string('subject');
      $table->text('message');
      $table->enum('status', ['open', 'inProgress', 'resolved', 'closed'])->default('open');
      $table->enum('priority', ['low', 'medium', 'high', 'urgent'])->default('medium');
      $table->unsignedBigInteger('assignedTo')->nullable();
      $table->timestamp('resolvedAt')->nullable();
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->foreign('userId')->references('userId')->on('users')->onDelete('cascade');
      $table->foreign('assignedTo')->references('userId')->on('users')->onDelete('set null');
      $table->index(['userId', 'status']);
    });
    Schema::create('ticketReplies', function (Blueprint $table) {
      $table->id('replyId');
      $table->unsignedBigInteger('ticketId');
      $table->unsignedBigInteger('userId');
      $table->text('message');
      $table->boolean('isStaffReply')->default(false);
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->foreign('ticketId')->references('ticketId')->on('supportTickets')->onDelete('cascade');
      $table->foreign('userId')->references('userId')->on('users')->onDelete('cascade');
    });
    Schema::create('verificationTokens', function (Blueprint $table) {
      $table->unsignedBigInteger('userId')->primary();
      $table->string('token');
      $table->timestamp('expiresAt');
      $table->timestamp('createdAt');
      $table->foreign('userId')->references('userId')->on('users')->onDelete('cascade');
      $table->index('token');
    });
    Schema::create('wallets', function (Blueprint $table) {
      $table->id('walletId');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->decimal('balance', 12, 2)->default(0);
      $table->decimal('pendingBalance', 12, 2)->default(0);
      $table->decimal('totalEarnings', 12, 2)->default(0);
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
      $table->unique('userId');
    });
    Schema::create('payouts', function (Blueprint $table) {
      $table->id('payoutId');
      $table->foreignId('instructorId')->constrained('users', 'userId')->onDelete('cascade');
      $table->decimal('amount', 12, 2);
      $table->enum('status', ['pending', 'processing', 'completed', 'failed'])->default('pending');
      $table->string('paymentMethod')->default('bankTransfer');
      $table->jsonb('bankInfo')->nullable();
      $table->text('adminNotes')->nullable();
      $table->timestamp('processedAt')->nullable();
      $table->foreignId('processedBy')->nullable()->constrained('users', 'userId')->onDelete('set null');
      $table->timestamp('createdAt')->nullable();
      $table->timestamp('updatedAt')->nullable();
    });
    Schema::create('ledgerEntries', function (Blueprint $table) {
      $table->id('ledgerId');
      $table->foreignId('walletId')->constrained('wallets', 'walletId')->onDelete('cascade');
      $table->foreignId('transactionId')->nullable()->constrained('paymentTransactions', 'transactionId')->onDelete('set null');
      $table->foreignId('payoutId')->nullable();
      $table->enum('type', ['credit', 'debit', 'escrowRelease', 'payout']);
      $table->decimal('amount', 12, 2);
      $table->decimal('balanceAfter', 12, 2);
      $table->string('description');
      $table->jsonb('metadata')->nullable();
      $table->timestamp('createdAt')->nullable();
    });
    Schema::create('quizzes', function (Blueprint $table) {
      $table->id('quizId');
      $table->unsignedBigInteger('courseId');
      $table->string('quizTitle');
      $table->integer('passingScore')->default(70);
      $table->integer('timeLimitMinutes')->nullable();
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->foreign('courseId')->references('courseId')->on('courses')->onDelete('cascade');
    });
    Schema::create('quizQuestions', function (Blueprint $table) {
      $table->id('questionId');
      $table->unsignedBigInteger('quizId');
      $table->text('questionText');
      $table->json('options');
      $table->integer('correctAnswer');
      $table->integer('orderIndex')->default(1);
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->foreign('quizId')->references('quizId')->on('quizzes')->onDelete('cascade');
    });
    Schema::create('quizAttempts', function (Blueprint $table) {
      $table->id('attemptId');
      $table->unsignedBigInteger('quizId');
      $table->unsignedBigInteger('userId');
      $table->integer('score');
      $table->json('answers');
      $table->timestamp('startedAt')->useCurrent();
      $table->timestamp('completedAt')->nullable();
      $table->foreign('quizId')->references('quizId')->on('quizzes')->onDelete('cascade');
      $table->foreign('userId')->references('userId')->on('users')->onDelete('cascade');
    });
    Schema::create('courseDiscussions', function (Blueprint $table) {
      $table->id('discussionId');
      $table->foreignId('courseId')->constrained('courses', 'courseId')->onDelete('cascade');
      $table->foreignId('userId')->constrained('users', 'userId')->onDelete('cascade');
      $table->unsignedBigInteger('parentId')->nullable();
      $table->string('title')->nullable();
      $table->text('content');
      $table->boolean('isPinned')->default(false);
      $table->boolean('isInstructorReply')->default(false);
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->foreign('parentId')->references('discussionId')->on('courseDiscussions')->onDelete('cascade');
      $table->index('courseId');
      $table->index('parentId');
    });
    Schema::create('blogs', function (Blueprint $table) {
      $table->id('blogId');
      $table->foreignId('instructorId')->constrained('users', 'userId')->onDelete('cascade');
      $table->string('title');
      $table->string('slug')->unique();
      $table->text('content');
      $table->string('thumbnail')->nullable();
      $table->boolean('isPublished')->default(false);
      $table->timestamp('publishedAt')->nullable();
      $table->integer('viewCount')->default(0);
      $table->timestamp('createdAt')->useCurrent();
      $table->timestamp('updatedAt')->useCurrent()->useCurrentOnUpdate();
      $table->index('instructorId');
      $table->index('slug');
      $table->index('isPublished');
    });
  }
  public function down(): void
  {
    Schema::dropIfExists('quizAttempts');
    Schema::dropIfExists('quizQuestions');
    Schema::dropIfExists('quizzes');
    Schema::dropIfExists('ledgerEntries');
    Schema::dropIfExists('payouts');
    Schema::dropIfExists('wallets');
    Schema::dropIfExists('verificationTokens');
    Schema::dropIfExists('ticketReplies');
    Schema::dropIfExists('supportTickets');
    Schema::dropIfExists('oauthProviders');
    Schema::dropIfExists('wishlists');
    Schema::dropIfExists('courseReviews');
    Schema::dropIfExists('certificates');
    Schema::dropIfExists('notifications');
    Schema::dropIfExists('assessmentSubmissions');
    Schema::dropIfExists('assessments');
    Schema::dropIfExists('progress');
    Schema::dropIfExists('paymentTransactions');
    Schema::dropIfExists('enrollments');
    Schema::dropIfExists('lessons');
    Schema::dropIfExists('modules');
    Schema::dropIfExists('courses');
    Schema::dropIfExists('categories');
    Schema::dropIfExists('passwordResetTokens');
    Schema::dropIfExists('users');
    Schema::dropIfExists('blogs');
    Schema::dropIfExists('courseDiscussions');
  }
};